Moved ll target to top of makefile to prevent "undefined reference to `__VERIFIER_nondet_int'" error when running 'make' due to a change which will be pushed to the modified Wool repo shortly.